### ISSUE TITLE
wp_delete_post causes SIGSEGV

### ISSUE THREAD

**Issue by larssn** [apkoponen/wp-rest-api-oauth2#4] opened 2016-11-08 15:31 UTC
Hey

So I'm currently testing how the code handles expired access_tokens.

I'm seeing an infinite loop. PHP-FPM makes a SIGSEGV after it has entered wp_delete_post on line 172'ish in class-oa2-token.php, which is odd.
So the child process dies, and phpfpm retries the entire operation again, but dying in the exact same spot. This is the only SIGSEGV that has ever happened on the server.

I've reported it to the php-fpm people, but I don't have high hopes about getting anything meaningful out of that.

Ideas?

This is on PHP 7.0.12, WP 4.6.1 and NGINX 1.11.5.

**Comment by apkoponen** [comment] 2016-11-08 16:15
Can you give steps to reproduce? You have an access token that has expired and you're trying to do a request with or how?

**Comment by larssn** [comment] 2016-11-08 16:19
Yes.

Try to reproduce by:
Whether you wanna install NGINX is up to you. But try with WP 4.6.1 (and PHP 7.0.12), and latest WooCommerce.
Go through the motions to set up your plugin, and test with postman. Modify the timestamp of the access token in the database, so it's expired.

Try to access: GET http://localhost/wp-json/wc/v1/orders

**Comment by larssn** [comment] 2016-11-08 16:20
I'm pretty sure its not the fault of your plugin, but who knows.

**Comment by apkoponen** [comment] 2016-11-08 18:11
Have you tried disabling all other plugins but WooCommerce and this one?

**Comment by apkoponen** [comment] 2016-11-08 18:40
I tried to reproduce the bug with the following steps (nginx/1.9.10, PHP Version 5.5.9-1ubuntu4.14):
1) Install latest WordPress & WooCommerce.
2) Create an access token.
3) Change the access token expiration in the wp_postmeta table to the past.
4) Try to GET /wp-json/wc/v1/orders with header Authorization: Bearer <TOKEN_HERE>

Result: The token is deleted from the database along with all of it's meta and the server responds with a 401:

```
{
  "code": "rest_oauth2_token_not_exists",
  "message": "Valtuutta ei ole olemassa.",
  "data": {
    "status": 401
  }
}
```

**Comment by larssn** [comment] 2016-11-09 09:06
Thanks for trying.

Was a long shot anyway, and I'm kinda strapped for time when it comes to debugging weird issues like these.

The dump file is here: https://cloud.nuvoweb.dk/_usr_sbin_php-fpm7.0.33.crash
If you wanna take a look.

EDIT
Managed to decode some of the crash file:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd5839b16a6 in pcre_exec () from /lib/x86_64-linux-gnu/libpcre.so.3

pcre is the regular expression module.

Might be this bug:
https://bugs.php.net/bug.php?id=73174
Then again, maybe not, since thats for php5

**Comment by apkoponen** [comment] 2016-11-09 18:39
It's not very rare to bump into weird issues if you have multiple WordPress plugins in the same installation. In pretty much everything has access to the global state and that's how weird bugs occur.

I'll go ahead a close this issue now, feel free to open it if you're able to reproduce the bug with just this plugin and WooCommerce enabled.

**Closed as completed by apkoponen** 2016-11-09 18:39 UTC

**Comment by larssn** [comment] 2016-11-10 08:38
Nah its fine. I've narrowed down the plugin that causes the problem - WooCommerce Bookings (which is a pile of dogshit code tbh)... 👎

**Comment by apkoponen** [comment] 2016-11-10 15:53
Haha! Been there, done that. We had performance issues with the plugin with even moderate amount of bookings. You'd expect better because it's developed by WooThemes themselves, but no.

Hope you get it solved. Cheers!

**Comment by larssn** [comment] 2016-11-10 16:20
Yeah I solved it. 💪 

Was redundant code that caused the problem anyway, so I ended up just removing it entirely.

We have a private branch at this point, where I'm fixing the various issues, as they pop up.
Shouldn't be my responsibility, but what can you do...

Are you still using it today?

**Comment by apkoponen** [comment] 2016-11-10 16:50
No, I'm not in not in that project anymore and I don't know if they had to trash the whole thing or what the current status is.

I think I spent a couple of whole days writing an elaborate caching system to the plugin that improved perf with something like 10x, but it never got to the core. They just weren't interested in improving the experience for bigger clients, I guess.

**Comment by larssn** [comment] 2016-11-10 16:56
A caching system? LOL! It really needs it!
We did some profiling, and it did something like 60k iterations of a big big chunk of code, just to render a single fucking icon in the frontend UI. I think the intern coded most of it... 😄 

We've almost replaced the entire frontend at this point, and soon we're gonna redo it, in Angular 2.

**Comment by apkoponen** [comment] 2016-11-10 18:29
Yea, we had a custom UI using https://fullcalendar.io/ through custom REST API endpoints. To us the worst part of the performance was the product page, because it looped through all the blocks for all the days every single time you would load the page. We had a 15 min minimum block and reservations could be made 1 year to the future which means 4_24_365 = 35040 blocks. Moreover, I think that loop was multiplied with the amount of reservations during the visible time period or something so the total number of loops was something in the ballpark of 1 000 000. I actually found a performance bug in the WP core during the perf tests back then: https://core.trac.wordpress.org/ticket/34368. 11 336 meta calls. :)

**Comment by larssn** [comment] 2016-11-10 18:36
That sounds about right. Gives me shudders, thinking about it. 😄 

I have a feeling that Woo isn't really prioritizing it at all anymore. I'm sure they know the codebase is almost unsalvagable. I say almost, because anything can be fixed, given will and time.
